---
kind: pipeline
type: docker
name: Drone - Discord Bot (Development)

clone:
  depth: 1

steps:

  - name: docker build & push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - ${DRONE_BRANCH}-latest

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: Drone - Discord Bot (Production)

clone:
  depth: 1

steps:

  - name: docker build & push (production)
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - prod-latest
        - prod-${DRONE_BUILD_NUMBER}


  - name: deploy
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      DISCORD_TOKEN:
        from_secret: discord_token_prod
    settings:
      inventory: .ansible/inventory/prod
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      extra_vars: version=prod
      private_key:
        from_secret: automation_id_rsa


trigger:
  branch:
    - stable
  event:
    - push

...
