---
kind: pipeline
type: docker
name: Build Server

clone:
  depth: 1

steps:

  - name: docker build and push
    image: plugins/docker
    settings:
      dockerfile: server.Dockerfile
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      purge: no
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}-server
      tags:
        - ${DRONE_BRANCH}-latest

trigger:
  branch:
    - development
    - stable
  event:
    - push

---

kind: pipeline
type: docker
name: Build Client

clone:
  depth: 1

steps:

  - name: docker build and push
    image: plugins/docker
    settings:
      dockerfile: client.Dockerfile
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      purge: no
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}-client
      tags:
        - ${DRONE_BRANCH}-latest

trigger:
  branch:
    - development
    - stable
  event:
    - push

---
kind: pipeline
type: docker
name: Deploy

clone:
  depth: 1

steps:

  - name: deploy (docker swarm)
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      DISCORD_TOKEN:
        from_secret: discord_token_prod
    settings:
      inventory: .ansible/inventory/stable
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa

trigger:
  branch:
    - stable
  event:
    - push

...
