---
kind: pipeline
type: docker
name: Build & Deploy (prod)

clone:
  depth: 1

concurrency:
  limit: 1

steps:

  - name: docker build & push (server)
    image: plugins/docker
    settings:
      dockerfile: server.Dockerfile
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      purge: no
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}-server
      tags:
        - ${DRONE_BRANCH}-latest

  - name: docker build & push (client)
    image: plugins/docker
    settings:
      dockerfile: client.Dockerfile
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      purge: no
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}-client
      tags:
        - ${DRONE_BRANCH}-latest

  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    environment:
      DRONE_WEBHOOK_SECRET:
        from_secret: drone_webhook_secret
      DISCORD_TOKEN:
        from_secret: discord_token
      DISCORD_CHANNEL_ID:
        from_secret: discord_channel_id
      SERVER_HOST:
        from_secret: server_host
      MONGO_PORT_EXPOSED:
        from_secret: mongo_port_exposed
      MONGO_INITDB_ROOT_USERNAME:
        from_secret: mongo_initdb_root_username
      MONGO_INITDB_ROOT_PASSWORD:
        from_secret: mongo_initdb_root_password
    settings:
      inventory: .ansible/inventories/prod.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa

trigger:
  branch:
    - stable
  event:
    - push

...
