- hosts: all
  strategy: free
  roles:
    - application
    - traefik

  tasks:

    - include_role:
        name: application
        tasks_from: make_data_dir
    
    - include_role:
        name: docker
        tasks_from: stack_deploy
